
version: '3.7'
services:
  test-pg:
    image: postgres:14.9-alpine
    container_name: test-pg
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - develop
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    logging:
      driver: json-file
      options:
        max-size: "100m"
        max-file: "5"


networks:
  develop:
    driver: bridge
